// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type GameStatus string

const (
	GameStatusSCHEDULED  GameStatus = "SCHEDULED"
	GameStatusINPROGRESS GameStatus = "IN_PROGRESS"
	GameStatusFINAL      GameStatus = "FINAL"
	GameStatusPOSTPONED  GameStatus = "POSTPONED"
	GameStatusSUSPENDED  GameStatus = "SUSPENDED"
)

func (e *GameStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GameStatus(s)
	case string:
		*e = GameStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GameStatus: %T", src)
	}
	return nil
}

type NullGameStatus struct {
	GameStatus GameStatus
	Valid      bool // Valid is true if GameStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGameStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GameStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GameStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGameStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GameStatus), nil
}

type AtBat struct {
	ID           uuid.UUID
	GameID       pgtype.UUID
	Inning       int32
	IsTopInning  bool
	BatterID     string
	PitcherID    string
	Result       pgtype.Text
	RunsScored   pgtype.Int4
	OutsRecorded pgtype.Int4
	CreatedAt    pgtype.Timestamptz
}

type Game struct {
	ID            uuid.UUID
	HomeTeamID    pgtype.Text
	AwayTeamID    pgtype.Text
	Status        NullGameStatus
	HomeScore     pgtype.Int4
	AwayScore     pgtype.Int4
	CurrentInning pgtype.Int4
	IsTopInning   pgtype.Bool
	StartTime     time.Time
	CreatedAt     pgtype.Timestamptz
}

type Pitch struct {
	ID            uuid.UUID
	AtBatID       pgtype.UUID
	PitchNumber   int32
	CoordinateX   pgtype.Numeric
	CoordinateY   pgtype.Numeric
	PitchResult   string
	BallsBefore   int32
	StrikesBefore int32
	OutsBefore    int32
	VelocityMph   pgtype.Numeric
	CreatedAt     pgtype.Timestamptz
}

type Team struct {
	ID        string
	Name      string
	ShortName string
	LogoUrl   pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
