// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAtBat = `-- name: CreateAtBat :one
INSERT INTO at_bats (
  game_id, inning, is_top_inning, batter_id, pitcher_id
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, game_id, inning, is_top_inning, batter_id, pitcher_id, result, runs_scored, outs_recorded, created_at
`

type CreateAtBatParams struct {
	GameID      pgtype.UUID
	Inning      int32
	IsTopInning bool
	BatterID    string
	PitcherID   string
}

func (q *Queries) CreateAtBat(ctx context.Context, arg CreateAtBatParams) (AtBat, error) {
	row := q.db.QueryRow(ctx, createAtBat,
		arg.GameID,
		arg.Inning,
		arg.IsTopInning,
		arg.BatterID,
		arg.PitcherID,
	)
	var i AtBat
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Inning,
		&i.IsTopInning,
		&i.BatterID,
		&i.PitcherID,
		&i.Result,
		&i.RunsScored,
		&i.OutsRecorded,
		&i.CreatedAt,
	)
	return i, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games (
  home_team_id, away_team_id, start_time
) VALUES (
  $1, $2, $3
)
RETURNING id, home_team_id, away_team_id, status, home_score, away_score, current_inning, is_top_inning, start_time, created_at
`

type CreateGameParams struct {
	HomeTeamID pgtype.Text
	AwayTeamID pgtype.Text
	StartTime  time.Time
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame, arg.HomeTeamID, arg.AwayTeamID, arg.StartTime)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.Status,
		&i.HomeScore,
		&i.AwayScore,
		&i.CurrentInning,
		&i.IsTopInning,
		&i.StartTime,
		&i.CreatedAt,
	)
	return i, err
}

const createPitch = `-- name: CreatePitch :one
INSERT INTO pitches (
  at_bat_id, pitch_number, coordinate_x, coordinate_y, 
  pitch_result, balls_before, strikes_before, outs_before, velocity_mph
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, at_bat_id, pitch_number, coordinate_x, coordinate_y, pitch_result, balls_before, strikes_before, outs_before, velocity_mph, created_at
`

type CreatePitchParams struct {
	AtBatID       pgtype.UUID
	PitchNumber   int32
	CoordinateX   pgtype.Numeric
	CoordinateY   pgtype.Numeric
	PitchResult   string
	BallsBefore   int32
	StrikesBefore int32
	OutsBefore    int32
	VelocityMph   pgtype.Numeric
}

func (q *Queries) CreatePitch(ctx context.Context, arg CreatePitchParams) (Pitch, error) {
	row := q.db.QueryRow(ctx, createPitch,
		arg.AtBatID,
		arg.PitchNumber,
		arg.CoordinateX,
		arg.CoordinateY,
		arg.PitchResult,
		arg.BallsBefore,
		arg.StrikesBefore,
		arg.OutsBefore,
		arg.VelocityMph,
	)
	var i Pitch
	err := row.Scan(
		&i.ID,
		&i.AtBatID,
		&i.PitchNumber,
		&i.CoordinateX,
		&i.CoordinateY,
		&i.PitchResult,
		&i.BallsBefore,
		&i.StrikesBefore,
		&i.OutsBefore,
		&i.VelocityMph,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentAtBat = `-- name: GetCurrentAtBat :one
SELECT id, game_id, inning, is_top_inning, batter_id, pitcher_id, result, runs_scored, outs_recorded, created_at FROM at_bats
WHERE game_id = $1
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetCurrentAtBat(ctx context.Context, gameID pgtype.UUID) (AtBat, error) {
	row := q.db.QueryRow(ctx, getCurrentAtBat, gameID)
	var i AtBat
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Inning,
		&i.IsTopInning,
		&i.BatterID,
		&i.PitcherID,
		&i.Result,
		&i.RunsScored,
		&i.OutsRecorded,
		&i.CreatedAt,
	)
	return i, err
}

const getGame = `-- name: GetGame :one
SELECT id, home_team_id, away_team_id, status, home_score, away_score, current_inning, is_top_inning, start_time, created_at FROM games
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGame(ctx context.Context, id uuid.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.Status,
		&i.HomeScore,
		&i.AwayScore,
		&i.CurrentInning,
		&i.IsTopInning,
		&i.StartTime,
		&i.CreatedAt,
	)
	return i, err
}

const getOutsForInning = `-- name: GetOutsForInning :one
SELECT COALESCE(SUM(outs_recorded), 0)::int FROM at_bats
WHERE game_id = $1 AND inning = $2 AND is_top_inning = $3
`

type GetOutsForInningParams struct {
	GameID      pgtype.UUID
	Inning      int32
	IsTopInning bool
}

func (q *Queries) GetOutsForInning(ctx context.Context, arg GetOutsForInningParams) (int32, error) {
	row := q.db.QueryRow(ctx, getOutsForInning, arg.GameID, arg.Inning, arg.IsTopInning)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getPitchesForAtBat = `-- name: GetPitchesForAtBat :many
SELECT id, at_bat_id, pitch_number, coordinate_x, coordinate_y, pitch_result, balls_before, strikes_before, outs_before, velocity_mph, created_at FROM pitches
WHERE at_bat_id = $1
ORDER BY pitch_number ASC
`

func (q *Queries) GetPitchesForAtBat(ctx context.Context, atBatID pgtype.UUID) ([]Pitch, error) {
	rows, err := q.db.Query(ctx, getPitchesForAtBat, atBatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pitch
	for rows.Next() {
		var i Pitch
		if err := rows.Scan(
			&i.ID,
			&i.AtBatID,
			&i.PitchNumber,
			&i.CoordinateX,
			&i.CoordinateY,
			&i.PitchResult,
			&i.BallsBefore,
			&i.StrikesBefore,
			&i.OutsBefore,
			&i.VelocityMph,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, short_name, logo_url, created_at FROM teams
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTeam(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.LogoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveGames = `-- name: ListActiveGames :many
SELECT id, home_team_id, away_team_id, status, home_score, away_score, current_inning, is_top_inning, start_time, created_at FROM games
WHERE status = 'IN_PROGRESS'
ORDER BY start_time DESC
`

func (q *Queries) ListActiveGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listActiveGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.Status,
			&i.HomeScore,
			&i.AwayScore,
			&i.CurrentInning,
			&i.IsTopInning,
			&i.StartTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, short_name, logo_url, created_at FROM teams
ORDER BY name
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortName,
			&i.LogoUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAtBatResult = `-- name: UpdateAtBatResult :one
UPDATE at_bats
SET 
  result = $2,
  runs_scored = $3,
  outs_recorded = $4
WHERE id = $1
RETURNING id, game_id, inning, is_top_inning, batter_id, pitcher_id, result, runs_scored, outs_recorded, created_at
`

type UpdateAtBatResultParams struct {
	ID           uuid.UUID
	Result       pgtype.Text
	RunsScored   pgtype.Int4
	OutsRecorded pgtype.Int4
}

func (q *Queries) UpdateAtBatResult(ctx context.Context, arg UpdateAtBatResultParams) (AtBat, error) {
	row := q.db.QueryRow(ctx, updateAtBatResult,
		arg.ID,
		arg.Result,
		arg.RunsScored,
		arg.OutsRecorded,
	)
	var i AtBat
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Inning,
		&i.IsTopInning,
		&i.BatterID,
		&i.PitcherID,
		&i.Result,
		&i.RunsScored,
		&i.OutsRecorded,
		&i.CreatedAt,
	)
	return i, err
}

const updateGame = `-- name: UpdateGame :one
UPDATE games
SET 
  status = $2,
  home_score = $3,
  away_score = $4,
  current_inning = $5,
  is_top_inning = $6
WHERE id = $1
RETURNING id, home_team_id, away_team_id, status, home_score, away_score, current_inning, is_top_inning, start_time, created_at
`

type UpdateGameParams struct {
	ID            uuid.UUID
	Status        NullGameStatus
	HomeScore     pgtype.Int4
	AwayScore     pgtype.Int4
	CurrentInning pgtype.Int4
	IsTopInning   pgtype.Bool
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, updateGame,
		arg.ID,
		arg.Status,
		arg.HomeScore,
		arg.AwayScore,
		arg.CurrentInning,
		arg.IsTopInning,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.Status,
		&i.HomeScore,
		&i.AwayScore,
		&i.CurrentInning,
		&i.IsTopInning,
		&i.StartTime,
		&i.CreatedAt,
	)
	return i, err
}
